name:                pp
version:             "2.11"
github:              "CDSoft/pp"
license:             GPL-3
author:              "Christophe Delord"
maintainer:          "cdsoft.fr"
copyright:           "2015-2019 Christophe Delord"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CDSoft/pp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
  - src
  - .stack-work
  c-sources:
  - .stack-work/PlantumlJar_c.c
  include-dirs:
  - .stack-work
  other-extensions:
  - CPP
  - ForeignFunctionInterface
  ghc-options:
  - -Wall
  - -Werror
  - -O3
  - -fwarn-unused-do-bind
  dependencies:
  - strict
  - process
  - time
  - temporary
  - directory
  - filepath
  - spreadsheet
  - explicit-exception
  - split
  - parsec
  - mustache
  - aeson
  - yaml
  - text
  - bytestring
  - unix-compat

executables:
  pp:
    main:                pp.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Werror
    - -O3
    - -fwarn-unused-do-bind
    dependencies:
    - pp

tests:
  pp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Werror
    - -O3
    - -fwarn-unused-do-bind
    dependencies:
    - pp
    - hspec
